spring:
  data:
    mongodb:
      #username: admin
      database: openarcana
      #password: 123456
      port: 27017
      host: localhost
  security:
    user:
      password: 123456

security:
  secret: ${SECURITY_SECRET:hello_world}
  expiration-in-hours: 1